services:
  web:
    profiles: ["dev"]
    environment:
      DEBUG: "True"
      DB_NAME: kamerka
      DB_USER: kamerka
      DB_PASSWORD: kamerka
      DB_PORT: "5432"
      DB_HOST: postgres
      ALLOWED_HOSTS: localhost,127.0.0.1
    volumes:
      - ./:/app
      - media_data:/app/scans
      - downloads_data:/app/downloads
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    profiles: ["dev"]
    environment:
      DEBUG: "True"
      DB_NAME: kamerka
      DB_USER: kamerka
      DB_PASSWORD: kamerka
      DB_PORT: "5432"
      DB_HOST: postgres
    volumes:
      - ./:/app
      - media_data:/app/scans
      - downloads_data:/app/downloads

  celery-beat:
    profiles: ["dev"]
    environment:
      DEBUG: "True"
      DB_NAME: kamerka
      DB_USER: kamerka
      DB_PASSWORD: kamerka
      DB_PORT: "5432"
      DB_HOST: postgres
    volumes:
      - ./:/app
      - media_data:/app/scans
      - downloads_data:/app/downloads
