# Generated by Django 4.2.28 on 2026-02-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinaryEdgeScore',
        ),
    ]
