# Generated by Django 4.2.28 on 2026-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0002_remove_binaryedgescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostnames',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
