# Generated by Django 4.2.28 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change Device.port from CharField(max_length=1000) to TextField so that
    nmap scans covering all 65 535 ports (~448 000 characters) can be stored
    without hitting PostgreSQL's varchar length limit.
    """

    dependencies = [
        ('app_kamerka', '0003_device_port_hostnames_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.TextField(default=''),
        ),
    ]
