# Generated by Django 4.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add Device.last_scanned (DateTimeField, nullable) for Shodan API
    deduplication.

    verification.shodan_analytics.should_skip_ip() queries this field to avoid
    redundant API calls for IPs that were scanned within the configured
    max_age_hours window (default: 24 h).  update_last_scanned() stamps it
    after every successful Shodan download.
    """

    dependencies = [
        ('app_kamerka', '0004_device_port_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_scanned',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text=(
                    'Timestamp of the most recent Shodan API scan for this IP. '
                    'Used by verification.shodan_analytics.should_skip_ip() to avoid '
                    'redundant API calls for recently-checked assets.'
                ),
            ),
        ),
    ]
