# Generated by Django 4.2.29 on 2026-03-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0005_device_last_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpe',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='device',
            name='isp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
