# Generated by Django 4.2.29 on 2026-03-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0006_add_isp_cpe_to_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(default='', max_length=30)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('epss_score', models.FloatField(default=0.0)),
                ('epss_percentile', models.FloatField(default=0.0)),
                ('kev_listed', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('exploit_available', models.BooleanField(default=False)),
                ('source', models.CharField(default='nvd', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kamerka.device')),
            ],
        ),
        migrations.CreateModel(
            name='SBOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(default='', max_length=200)),
                ('version', models.CharField(default='', max_length=100)),
                ('component_type', models.CharField(default='library', max_length=50)),
                ('license_name', models.CharField(default='', max_length=100)),
                ('cpe_string', models.CharField(default='', max_length=300)),
                ('source', models.CharField(default='', max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kamerka.device')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='', max_length=50)),
                ('vendor_id', models.CharField(default='', max_length=200)),
                ('project_name', models.CharField(default='', max_length=200)),
                ('hardware_version', models.CharField(default='', max_length=200)),
                ('firmware_version', models.CharField(default='', max_length=200)),
                ('serial_number', models.CharField(default='', max_length=200)),
                ('module_name', models.CharField(default='', max_length=200)),
                ('slave_id', models.CharField(default='', max_length=100)),
                ('plant_id', models.CharField(default='', max_length=200)),
                ('raw_output', models.TextField(default='')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kamerka.device')),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('reasons', models.TextField(default='')),
                ('banner_count_in_subnet', models.IntegerField(default=0)),
                ('is_conpot', models.BooleanField(default=False)),
                ('is_cowrie', models.BooleanField(default=False)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kamerka.device')),
            ],
        ),
        migrations.CreateModel(
            name='GFWStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reachable', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('ooni_report_id', models.CharField(default='', max_length=200)),
                ('blocking_type', models.CharField(default='', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kamerka.device')),
            ],
        ),
    ]
