# Generated by Django 4.2.30 on 2026-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0008_vulnintelligence_exploit_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='exploit',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_scanned',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent Shodan API scan for this IP. Used by verification.shodan_analytics.should_skip_ip() to avoid redundant API calls for recently-checked assets.', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='scan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='screenshot',
            field=models.TextField(default=''),
        ),
    ]
