# Generated by Django 4.2.30 on 2026-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0009_device_field_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vulns',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shodanscan',
            name='vulns',
            field=models.TextField(default=''),
        ),
    ]
