# Generated by Django 4.2.30 on 2026-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0010_widen_vulns_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnintelligence',
            name='propose_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vulnintelligence',
            name='ransomware_campaign',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
