# Generated by Django 4.2.30 on 2026-05-20 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_kamerka', '0012_device_risk_score_layer_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tool', models.CharField(choices=[('wappalyzer', 'Wappalyzer'), ('nuclei', 'Nuclei'), ('nmap', 'Nmap'), ('port_scan', 'Port Scan'), ('screenshot', 'Screenshot'), ('rtsp', 'RTSP'), ('shodan_scan', 'Shodan Scan'), ('whois', 'Whois'), ('nearby', 'Nearby'), ('deep_scan', 'Deep Scan'), ('nvd', 'NVD'), ('nrich', 'NRICH'), ('cvedb', 'CVEDB'), ('intel', 'Shodan Intel'), ('honeypot', 'Honeypot'), ('sbom', 'SBOM'), ('gfw', 'GFW'), ('exploitdb', 'ExploitDB'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_name', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_kamerka.device')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_kamerka.search')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
