# Generated by Django 4.2.30 on 2026-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0013_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('query_type', models.CharField(choices=[('country', 'Country'), ('coordinates', 'Coordinates')], default='country', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('query_items', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(default='ics', max_length=100)),
                ('healthcare', models.BooleanField(default=False)),
                ('all_results', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('refresh_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
