# Generated by Django 4.2.30 on 2026-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0016_playbook_playbookrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shodanscan',
            name='module',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shodanscan',
            name='ports',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shodanscan',
            name='products',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shodanscan',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
